name: Continous Integration

on:
  push:
    branches: [ main ]


jobs:

  simpleTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: |
          npm start &
          sleep 2
          npm test